[package]
name = "ufork-wasm"
version = "0.1.0"
authors = ["Dale Schumacher <dalnefre@yahoo.com>"]
edition = "2018"
description = "uFork VM in Rust targeting WASM"
repository = "https://github.com/organix/uFork/tree/main/ufork-wasm"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []

[dependencies]

[dev-dependencies]

[profile.release]
opt-level = "s"					# optimize for small code size.
